In [2]:
import pandas as pd

In [2]:
# Create from dictionary
data = {
    "name" : ["Sumed", "Rahul", "Priya"],
    "age"  : [22, 45, 33],
    "bp"   : [119, 135, 108]
}

df = pd.DataFrame(data)
print(df)

    name  age   bp
0  Sumed   22  119
1  Rahul   45  135
2  Priya   33  108

df.head()        # Show first 5 rows

df.tail()        # Show last 5 rows

df.shape         # (rows, columns) count

df.info()        # Data types of each column

df.describe()    # Statistics summary

In [4]:


data = {
    "name"  : ["r", "p", "k"],
    "marks" : [1, 2, 3],
    "grade" : ["A", "B", "C"]
}

df = pd.DataFrame(data)

# Print DataFrame
print(df)

# Print shape
print(df.shape)

  name  marks grade
0    r      1     A
1    p      2     B
2    k      3     C
(3, 3)

pd.DataFrame()     # Open pd toolbox → pick DataFrame tool
pd.read_csv()      # Open pd toolbox → pick read_csv tool
pd.merge()         # Open pd toolbox → pick merge tool
```

---

### Real Life Analogy 🔧
```
pd          = Your toolbox
.           = Open the toolbox
DataFrame   = The specific tool you need

# ACTIONS — need brackets ()
print(df)           # does something → displays
df.head()           # does something → shows first 5 rows
df.describe()       # does something → calculates statistics
df.dropna()         # does something → removes empty rows

# VALUES — no brackets
df.shape            # just holds → (rows, columns)
df.columns          # just holds → column names
df.index            # just holds → row numbers
df.dtypes           # just holds → data types
```

---

### Simple Rule Forever 💡
```
Ask yourself — "Is this DOING something or just STORING something?"

DOING something  → needs ()
STORING something → no ()

## Creating DataFrame

In [21]:

# Create a DataFrame from a dictionary

data = {
    'EmpID':  [101, 102, 103, 104, 105],
    'Name':   ['Sumed', 'Priya', 'Rahul', 'Neha', 'Arjun'],
    'Dept':   ['Data', 'HR', 'Data', 'Finance', 'Data'],
    'Salary': [60000, 45000, 75000, 55000, 80000],
    'Exp':    [3, 2, 5, 4, 6]
}
df = pd.DataFrame(data)
print(df)

   EmpID   Name     Dept  Salary  Exp
0    101  Sumed     Data   60000    3
1    102  Priya       HR   45000    2
2    103  Rahul     Data   75000    5
3    104   Neha  Finance   55000    4
4    105  Arjun     Data   80000    6

## Exploring the DataFrame

In [ ]:
# Key methods to explore any DataFrame
df.head(2)       # first 2 rows
df.tail(2)       # last 2 rows
df.shape          # (rows, columns)
df.columns        # column names
df.dtypes         # data types of each column
df.info()          # summary of the whole df
df.describe()      # stats for numeric columns

In [22]:
df.describe()

            EmpID        Salary       Exp
count    5.000000      5.000000  5.000000
mean   103.000000  63000.000000  4.000000
std      1.581139  14404.860291  1.581139
min    101.000000  45000.000000  2.000000
25%    102.000000  55000.000000  3.000000
50%    103.000000  60000.000000  4.000000
75%    104.000000  75000.000000  5.000000
max    105.000000  80000.000000  6.000000

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EmpID   5 non-null      int64
 1   Name    5 non-null      object
 2   Dept    5 non-null      object
 3   Salary  5 non-null      int64
 4   Exp     5 non-null      int64
dtypes: int64(3), object(2)
memory usage: 328.0+ bytes

In [25]:
df.dtypes         # data types of each column

EmpID      int64
Name      object
Dept      object
Salary     int64
Exp        int64
dtype: object

## Selecting Data

In [ ]:
# Select a single column → returns a Series
df['Name']

# Select multiple columns → returns a DataFrame
df[['Name', 'Salary']]

# Select rows by index → .iloc (integer location)
df.iloc[0]        # first row
df.iloc[1:3]      # rows 1 and 2

# Select rows by label → .loc
df.loc[0, 'Name']  # row 0, Name column

In [26]:
# Select multiple columns → returns a DataFrame
df[['Name', 'Salary']]

    Name  Salary
0  Sumed   60000
1  Priya   45000
2  Rahul   75000
3   Neha   55000
4  Arjun   80000

In [27]:
# Select rows by index → .iloc (integer location)
df.iloc[0]        # first row
df.iloc[1:4]      # rows 1 and 3

   EmpID   Name     Dept  Salary  Exp
1    102  Priya       HR   45000    2
2    103  Rahul     Data   75000    5
3    104   Neha  Finance   55000    4

In [31]:
df.iloc[-1]

EmpID       105
Name      Arjun
Dept       Data
Salary    80000
Exp           6
Name: 4, dtype: object

In [32]:
df.iloc[1:3]        # rows 1 and 2 (3 is excluded)

   EmpID   Name  Dept  Salary  Exp
1    102  Priya    HR   45000    2
2    103  Rahul  Data   75000    5

In [33]:
df.iloc[0, 1]       # row 0, column 1 → 'Sumed'

'Sumed'

In [34]:
df.iloc[0:3, 1:3]   # rows 0-2, cols 1-2

    Name  Dept
0  Sumed  Data
1  Priya    HR
2  Rahul  Data

In [35]:
df.iloc[:, 0]       # ALL rows, first column only

0    101
1    102
2    103
3    104
4    105
Name: EmpID, dtype: int64

In [36]:
df.iloc[:, -1]      # ALL rows, last column

0    3
1    2
2    5
3    4
4    6
Name: Exp, dtype: int64

In [29]:
# Select rows by label → .loc
df.loc[2, 'Dept']  # row 0, Name column

'Data'

In [ ]:
# loc → "label location" → uses index labels & column names
# Syntax: df.loc[row_label, col_label]
# IMPORTANT: loc end is INCLUSIVE (unlike iloc)

df.loc[0]                      # row with index label 0
df.loc[0, 'Name']             # single value → 'Sumed'

0    60000
1    45000
2    75000
3    55000
4    80000
Name: Salary, dtype: int64

In [40]:
df.loc[0:2, 'Name':'Dept']    # rows 0,1,2 — cols Name,Dept

    Name  Dept
0  Sumed  Data
1  Priya    HR
2  Rahul  Data

In [41]:
df.loc[:, 'Salary']            # all rows, Salary column

0    60000
1    45000
2    75000
3    55000
4    80000
Name: Salary, dtype: int64

In [37]:
# Setting a custom index changes loc behavior
df2 = df.set_index('EmpID')
df2.loc[103]                   # now fetch by EmpID, not 0,1,2
df2.loc[103, 'Salary']         # → 75000

np.int64(75000)

In [44]:
# .at and .iat → for accessing a SINGLE cell only
# Faster than loc/iloc for single value access

df.at[2, 'Salary']    # label-based → 75000 (same as loc but faster)


# When would you use this?
# When looping over millions of rows — .at/.iat are faster
# For normal analysis, loc/iloc is fine

np.int64(75000)

In [45]:
df.iat[2, 3]           # position-based → 75000 (row 2, col 3)

np.int64(75000)