## 📖 Topic 3 — Filtering & Conditions

1. What is filtering?


In real projects, you never work with the full dataset. You always need a subset — "show me only Data dept employees", "find customers who spent more than ₹10,000", "get all records from 2024". That's filtering.


Pandas does this using something called a Boolean Mask.

2. What is a Boolean Mask?


When you write a condition on a column, Pandas doesn't give you the data directly. It first creates a Series of True/False values — one for each row. Then it uses that to filter.

In [1]:
import pandas as pd

data = {
    'Name':   ['Sumed', 'Priya', 'Rahul', 'Neha', 'Arjun'],
    'Dept':   ['Data', 'HR', 'Data', 'Finance', 'Data'],
    'Salary': [60000, 45000, 75000, 55000, 80000],
    'Exp':    [3, 2, 5, 4, 6]
}
df = pd.DataFrame(data)

In [2]:
df

    Name     Dept  Salary  Exp
0  Sumed     Data   60000    3
1  Priya       HR   45000    2
2  Rahul     Data   75000    5
3   Neha  Finance   55000    4
4  Arjun     Data   80000    6

In [3]:
# Step 1: condition creates a boolean mask
mask = df['Salary'] > 60000
print(mask)

# Step 2: pass mask into df[] to filter rows
df[mask]

# One-liner (most common style in real code)
df[df['Salary'] > 60000]

0    False
1    False
2     True
3    False
4     True
Name: Salary, dtype: bool

    Name  Dept  Salary  Exp
2  Rahul  Data   75000    5
4  Arjun  Data   80000    6

In [7]:
# & → AND (both conditions must be True)
df[(df['Dept'] == 'Data') & (df['Salary'] > 60000)]


# WHY parentheses around each condition?
# & and | have higher precedence than == > <
# Without () Python evaluates wrong — always wrap each condition

    Name  Dept  Salary  Exp
2  Rahul  Data   75000    5
4  Arjun  Data   80000    6

In [5]:
# ~ → NOT (inverts the condition)
df[~(df['Dept'] == 'Data')]   # everyone NOT in Data dept

    Name     Dept  Salary  Exp
1  Priya       HR   45000    2
3   Neha  Finance   55000    4

In [6]:
# | → OR (at least one condition must be True)
df[(df['Dept'] == 'HR') | (df['Salary'] > 70000)]

    Name  Dept  Salary  Exp
1  Priya    HR   45000    2
2  Rahul  Data   75000    5
4  Arjun  Data   80000    6