## Dropping Rows & Columns

* Why does this matter?
Real world datasets are messy. You'll always have columns you don't need (like ID, timestamp, irrelevant metadata), and rows that are garbage (duplicates, test entries, corrupted records). Keeping them pollutes your analysis. Dropping is one of the first things you do in any data cleaning task.
* The core method — drop()
* What is it?
drop() is the primary Pandas method to remove rows or columns from a DataFrame.

* Why one method for both rows and columns?

Because Pandas uses the axis parameter to distinguish — *axis=0* means rows,

 *axis=1* means columns. Same method, different direction. You already know 
 
 *axis* from *apply()* — same concept here.
* How does it work?

You tell Pandas what labels to drop, and which axis to look along. Pandas finds those labels and removes them, returning a new DataFrame

In [1]:
import pandas as pd

data = {
    'Name':    ['Sumed', 'Priya', 'Rahul', 'Neha', 'Arjun'],
    'Dept':    ['Data', 'HR', 'Data', 'Finance', 'Data'],
    'Salary':  [60000, 45000, 75000, 55000, 80000],
    'Exp':     [3, 2, 5, 4, 6],
    'Temp_ID': ['T1', 'T2', 'T3', 'T4', 'T5']  # irrelevant column
}
df = pd.DataFrame(data)

In [2]:
df

    Name     Dept  Salary  Exp Temp_ID
0  Sumed     Data   60000    3      T1
1  Priya       HR   45000    2      T2
2  Rahul     Data   75000    5      T3
3   Neha  Finance   55000    4      T4
4  Arjun     Data   80000    6      T5

## Drop a single column

In [3]:
# drop() syntax: df.drop(labels, axis)
# axis=1 means we are working along the column direction
# axis=0 means we are working along the row direction

# Drop single column — returns new df, original unchanged
df.drop('Temp_ID', axis=1)

# Cleaner alternative using 'columns' keyword
# No need to write axis=1 — more readable
df.drop(columns='Temp_ID')

# To actually save the result, reassign
df = df.drop(columns='Temp_ID')

In [4]:
df

    Name     Dept  Salary  Exp
0  Sumed     Data   60000    3
1  Priya       HR   45000    2
2  Rahul     Data   75000    5
3   Neha  Finance   55000    4
4  Arjun     Data   80000    6

*drop(columns=...) is preferred over drop(..., axis=1) — it's more explicit and readable. Both do exactly the same thing.*